name: Auto Release OTA

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build Update Zip
      run: |
        npm run build
        cd dist/cep
        zip -r ../../update.zip ./*
        cd ../..
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: update.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
